%define INSTANCEHOME D:\Coding\ALims\senaite.lims
instancehome $INSTANCEHOME

%define CLIENTHOME $INSTANCEHOME/var/instance
clienthome $CLIENTHOME

debug-mode on
security-policy-implementation C
verbose-security off
default-zpublisher-encoding utf-8

<environment>
    CHAMELEON_CACHE $INSTANCEHOME/var/cache
    zope_i18n_compile_mo_files true
</environment>

<zodb_db main>
    <filestorage>
        path $INSTANCEHOME/var/filestorage/Data.fs
        blob-dir $INSTANCEHOME/var/blobstorage
    </filestorage>
    mount-point /
</zodb_db>
